apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslo-app
  labels:
    app: teslo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teslo-app
  template:
    metadata:
      labels:
        app: teslo-app
    spec:
      containers:
      - name: teslo-app
        image: my-docker-username/teslo-app:${GITHUB_SHA}  # Usando el hash del commit para la imagen
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: teslo-app-service
spec:
  selector:
    app: teslo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
